ALTER TABLE "VehicleImport"
ADD COLUMN "towingCostUsd" DECIMAL(12,2) NOT NULL DEFAULT 0,
ADD COLUMN "oceanFreightUsd" DECIMAL(12,2) NOT NULL DEFAULT 0,
ADD COLUMN "paidAmountUsd" DECIMAL(12,2) NOT NULL DEFAULT 0;
