import { IoArrowDownOutline, IoBoatOutline, IoCameraOutline, IoDocumentTextOutline, IoLocationOutline, IoLogoWhatsapp, IoShieldCheckmarkOutline } from "react-icons/io5";

import { siteConfig } from "@/config/site";

const whatsappMessage = "Hola, me interesa cotizar el servicio de importación de vehículos desde Estados Unidos a Chile.";

export function LogisticsServiceSection() {
  return <section id="importacion-vehiculos" className="overflow-hidden bg-slate-950 py-20 text-white">
    <div className="mx-auto max-w-7xl px-6"><div className="grid items-center gap-12 lg:grid-cols-[1.05fr_.95fr]">
      <div><span className="inline-flex items-center gap-2 rounded-full border border-blue-400/30 bg-blue-500/10 px-4 py-2 text-sm font-bold text-blue-300"><IoBoatOutline aria-hidden="true"/> Logística internacional de vehículos</span><h2 className="mt-6 max-w-3xl text-4xl font-black leading-tight sm:text-5xl">Importamos tu vehículo desde <span className="text-blue-400">Estados Unidos</span> hasta Chile</h2><p className="mt-5 max-w-2xl text-lg leading-8 text-slate-300">Realizamos el servicio logístico para trasladar vehículos desde Estados Unidos hacia Arica e Iquique, con registro fotográfico, documentación y seguimiento de cada etapa.</p>
        <div className="mt-8 grid gap-3 sm:grid-cols-3">{[[IoCameraOutline, "Registro fotográfico"], [IoDocumentTextOutline, "Documentos centralizados"], [IoShieldCheckmarkOutline, "Seguimiento privado"]].map(([Icon, text]) => <div key={String(text)} className="flex items-center gap-3 rounded-2xl border border-white/10 bg-white/5 p-4"><Icon className="h-6 w-6 shrink-0 text-blue-400"/><span className="text-sm font-bold">{String(text)}</span></div>)}</div>
        <a href={`https://wa.me/${siteConfig.whatsapp}?text=${encodeURIComponent(whatsappMessage)}`} target="_blank" rel="noreferrer" className="mt-8 inline-flex items-center gap-2 rounded-full bg-emerald-600 px-6 py-3.5 font-black text-white shadow-lg transition hover:bg-emerald-700"><IoLogoWhatsapp aria-hidden="true" className="h-5 w-5"/> Cotizar una importación</a>
      </div>
      <div className="relative rounded-[2.5rem] border border-white/10 bg-gradient-to-br from-blue-600/20 to-white/5 p-6 shadow-2xl sm:p-8"><p className="text-xs font-black uppercase tracking-[0.2em] text-blue-300">Ruta del servicio</p><div className="mt-5 rounded-3xl border border-blue-400/20 bg-slate-900/80 p-5"><div className="flex items-center gap-4"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-blue-600 text-xl font-black">US</span><div><p className="text-xs uppercase tracking-wider text-slate-400">Origen</p><strong className="text-lg">Estados Unidos</strong></div></div></div><div className="flex h-14 items-center pl-9"><IoArrowDownOutline className="h-6 w-6 text-blue-400"/><span className="ml-3 text-sm font-bold text-slate-400">Transporte y seguimiento</span></div><div className="grid gap-3 sm:grid-cols-2">{["Arica, Chile", "Iquique, Chile"].map((city) => <div key={city} className="flex items-center gap-3 rounded-2xl bg-white p-4 text-slate-950"><span className="grid h-10 w-10 place-items-center rounded-xl bg-blue-100 text-blue-700"><IoLocationOutline aria-hidden="true" className="h-5 w-5"/></span><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Destino</p><strong>{city}</strong></div></div>)}</div><div className="mt-6 grid grid-cols-5 gap-1">{["Por recibir", "Recibido", "Asignado", "Cargado", "Embarcado"].map((step, index) => <div key={step} className="text-center"><span className="mx-auto grid h-8 w-8 place-items-center rounded-full bg-blue-600 text-xs font-black">{index + 1}</span><p className="mt-2 text-[10px] font-bold text-slate-300 sm:text-[11px]">{step}</p></div>)}</div></div>
    </div></div>
  </section>;
}
