import Link from "next/link";
import { notFound } from "next/navigation";

import { addVehicleImportAttachmentsAction, addVehicleImportImagesAction, addVehicleImportNoteAction, deleteVehicleImportAttachmentAction, updateVehicleImportStatusAction } from "@/app/actions/imports";
import { DeleteMediaButton, ImportFinanceSummary, ImportImageGallery, ImportStatusTimeline, StyledSelect } from "@/components";
import { requireStaff } from "@/lib/auth";
import { db } from "@/lib/db";
import { formatImportDate, importStatusSteps, keyStatusLabels, titleStatusLabels } from "@/lib/import-status";

export const dynamic = "force-dynamic";

const value = (input: string | number | null | undefined) => input == null || input === "" ? "—" : String(input);

export default async function AdminImportDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ ok?: string; error?: string }> }) {
  await requireStaff();
  const { id } = await params;
  const item = await db.vehicleImport.findUnique({
    where: { id },
    include: {
      customer: { select: { firstName: true, lastName: true, email: true, phone: true } },
      images: { orderBy: { position: "asc" }, select: { id: true, filename: true } },
      attachments: { orderBy: { createdAt: "asc" }, select: { id: true, filename: true, size: true } },
      notes: { orderBy: { createdAt: "desc" }, include: { author: { select: { firstName: true, lastName: true } } } },
      parts: { orderBy: { position: "asc" }, include: { make: { select: { name: true } }, model: { select: { name: true } } } },
    },
  });
  if (!item) notFound();
  const query = await searchParams;
  const importName = item.importType === "PARTS" ? `Repuestos y autopartes` : `${item.year} ${item.make} ${item.model}`;
  return <main className="mx-auto max-w-7xl px-6 py-10">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><Link href="/admin/imports" className="text-sm font-bold text-blue-700">← Volver a importaciones</Link><p className="mt-3 text-xs font-black uppercase tracking-wider text-blue-700">{item.importType === "PARTS" ? "Repuestos" : "Vehículo"} · {item.referenceCode}</p><h1 className="mt-1 text-4xl font-black">{importName}</h1><p className="mt-1 text-slate-500">{item.importType === "PARTS" ? `${item.parts.length} ${item.parts.length === 1 ? "pieza" : "piezas"}${item.lotNumber ? ` · Lote ${item.lotNumber}` : ""}` : `VIN ${item.vin}${item.lotNumber ? ` · Lote ${item.lotNumber}` : ""}`}</p><Link href={`/admin/imports/${item.id}/edit`} className="mt-4 inline-flex rounded-xl border border-blue-200 bg-blue-50 px-4 py-2 text-sm font-bold text-blue-700 hover:bg-blue-100">Editar datos</Link></div><form action={updateVehicleImportStatusAction} className="flex min-w-72 flex-wrap items-end gap-2 rounded-2xl border bg-white p-3"><input type="hidden" name="id" value={item.id}/><div className="min-w-48 flex-1"><StyledSelect name="status" label="Estado" defaultValue={item.status} options={importStatusSteps}/></div><button className="rounded-xl bg-blue-700 px-4 py-3 font-bold text-white">Actualizar</button></form></div>
    {query.ok && <p className="mt-5 rounded-xl bg-emerald-50 p-3 font-semibold text-emerald-800">Los cambios se guardaron correctamente.</p>}{query.error && <p role="alert" className="mt-5 rounded-xl bg-red-50 p-3 font-semibold text-red-700">{query.error === "zip" ? "El ZIP debe ser válido, pesar máximo 30 MB y contener imágenes JPG, PNG o WebP." : query.error === "attachments" ? "Selecciona entre 1 y 5 archivos PDF o imágenes de máximo 5 MB cada uno." : "No se pudo modificar el archivo solicitado."}</p>}
    <section className="mt-7 rounded-3xl border bg-white p-6"><h2 className="text-xl font-black">Seguimiento</h2><div className="mt-4"><ImportStatusTimeline status={item.status}/></div></section>
    <div className="mt-6"><ImportFinanceSummary importType={item.importType as "VEHICLE" | "PARTS"} valueUsd={item.valueUsd ? Number(item.valueUsd) : 0} towingCostUsd={Number(item.towingCostUsd)} oceanFreightUsd={Number(item.oceanFreightUsd)} shippingCostUsd={Number(item.shippingCostUsd)} logisticsServiceUsd={Number(item.logisticsServiceUsd)} paidAmountUsd={Number(item.paidAmountUsd)} /></div>
    <div className="mt-6 grid gap-6 lg:grid-cols-[1.1fr_.9fr]">
      <div className="space-y-6"><section className="rounded-3xl border bg-white p-6"><h2 className="text-xl font-black">Imágenes</h2><div className="mt-4"><ImportImageGallery images={item.images} vehicleName={importName} importId={item.id} editable/></div><div className="mt-6 border-t pt-5"><h3 className="font-black">Añadir imágenes</h3><form action={addVehicleImportImagesAction} className="mt-3 flex flex-col gap-3 sm:flex-row"><input type="hidden" name="importId" value={item.id}/><input required type="file" name="imageZip" accept=".zip,application/zip" className="min-w-0 flex-1 rounded-xl border bg-white px-3 py-2 text-sm file:mr-3 file:rounded-lg file:border-0 file:bg-blue-50 file:px-3 file:py-2 file:font-bold file:text-blue-700"/><button className="rounded-xl bg-blue-700 px-4 py-2 font-bold text-white">Añadir ZIP</button></form><p className="mt-2 text-xs text-slate-500">Añade todas las imágenes del ZIP; máximo 30 MB y sin límite de cantidad.</p></div></section>
      <section className="rounded-3xl border bg-white p-6"><h2 className="text-xl font-black">Notas</h2><form action={addVehicleImportNoteAction} className="mt-4"><input type="hidden" name="id" value={item.id}/><textarea name="body" required maxLength={2000} rows={4} placeholder="Escribe una nota…" className="w-full rounded-2xl border p-3"/><label className="mt-2 flex items-center gap-2 text-sm"><input name="visibleToCustomer" type="checkbox" defaultChecked/> Visible para el cliente</label><button className="mt-3 rounded-xl bg-slate-900 px-4 py-2 font-bold text-white">Agregar nota</button></form><div className="mt-5 space-y-3">{item.notes.map((note) => <article key={note.id} className="rounded-2xl bg-slate-50 p-4"><p className="whitespace-pre-wrap">{note.body}</p><p className="mt-2 text-xs text-slate-500">{note.author ? `${note.author.firstName} ${note.author.lastName}` : "Sistema"} · {note.createdAt.toLocaleString("es-CL")} · {note.visibleToCustomer ? "Visible para el cliente" : "Nota interna"}</p></article>)}{!item.notes.length && <p className="text-slate-500">No hay notas todavía.</p>}</div></section></div>
      <div className="space-y-6">
        {item.importType === "PARTS" ? <ImportedParts parts={item.parts}/> : <><Section title="Identidad"><Row label="VIN" text={value(item.vin)}/><Row label="Año" text={value(item.year)}/><Row label="Marca" text={value(item.make)}/><Row label="Modelo" text={value(item.model)}/><Row label="Color" text={value(item.color)}/><Row label="N.º de lote" text={value(item.lotNumber)}/><Row label="Peso" text={item.weightKg ? `${item.weightKg} kg` : "—"}/><Row label="Tipo de carga" text={value(item.loadType)}/><Row label="Puerto de destino" text={value(item.destinationPort)}/><Row label="Fecha de recepción" text={formatImportDate(item.receivedDate)}/><Row label="Carga peligrosa" text={item.hazmat ? "Sí (HAZMAT)" : "No"}/><Row label="Combustible" text={value(item.fuel)}/></Section><Section title="Título y llaves"><Row label="Llaves" text={keyStatusLabels[item.keyStatus] ?? item.keyStatus}/><Row label="Título" text={titleStatusLabels[item.titleStatus] ?? item.titleStatus}/><Row label="Número de título" text={value(item.titleNumber)}/><Row label="Estado" text={value(item.titleState)}/><Row label="Schedule B / HTS" text={value(item.scheduleB)}/></Section></>}
        <Section title="Partes de la importación"><Row label="Cliente asignado" text={`${item.customer.firstName} ${item.customer.lastName}`}/><Row label="Correo" text={item.customer.email}/><Row label="Teléfono" text={value(item.customer.phone)}/><Row label="Número de contenedor" text={value(item.containerNumber)}/><Row label="Naviera" text={value(item.shippingLine)}/><Row label="Fecha de embarque" text={formatImportDate(item.departureDate)}/><Row label="Fecha de llegada" text={formatImportDate(item.arrivalDate)}/><Row label="Lugar de llegada" text={value(item.arrivalPlace)}/></Section>
        <Section title="Adjuntos"><form action={addVehicleImportAttachmentsAction} className="rounded-2xl border border-dashed border-blue-200 bg-blue-50/50 p-3"><input type="hidden" name="importId" value={item.id}/><input required multiple type="file" name="attachments" accept="application/pdf,image/jpeg,image/png,image/webp" className="w-full rounded-xl border bg-white px-2 py-2 text-sm file:mr-2 file:rounded-lg file:border-0 file:bg-blue-50 file:px-2 file:py-2 file:font-bold file:text-blue-700"/><button className="mt-2 w-full rounded-xl bg-blue-700 px-4 py-2 font-bold text-white">Añadir archivos</button><p className="mt-2 text-xs text-slate-500">Hasta 5 PDF o imágenes por carga, máximo 5 MB cada uno.</p></form>{item.attachments.map((file) => <div key={file.id} className="flex items-center gap-2 rounded-xl border p-2"><a href={`/api/import-attachments/${file.id}`} className="min-w-0 flex-1 truncate p-1 font-semibold text-blue-700 hover:underline">{file.filename} <span className="text-xs font-normal text-slate-500">({Math.ceil(file.size / 1024)} KB)</span></a><form action={deleteVehicleImportAttachmentAction}><input type="hidden" name="importId" value={item.id}/><input type="hidden" name="attachmentId" value={file.id}/><DeleteMediaButton kind="archivo"/></form></div>)}{!item.attachments.length && <p className="text-slate-500">No hay adjuntos.</p>}</Section>
      </div>
    </div>
  </main>;
}

function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-3xl border bg-white p-6"><h2 className="mb-4 text-xl font-black">{title}</h2><div className="space-y-2">{children}</div></section>; }
function Row({ label, text }: { label: string; text: string | number }) { return <div className="grid grid-cols-[minmax(0,1fr)_minmax(0,1.4fr)] gap-4 border-b border-slate-100 py-2 last:border-0"><dt className="text-sm text-slate-500">{label}</dt><dd className="break-words text-right font-semibold">{text}</dd></div>; }
function ImportedParts({ parts }: { parts: Array<{ id: string; description: string; partNumber: string; partBrand: string | null; quantity: number; unitValueUsd: unknown; weightKg: unknown; yearFrom: number; yearTo: number; engine: string | null; make: { name: string }; model: { name: string } }> }) { return <Section title="Repuestos importados">{parts.map((part) => <article key={part.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex justify-between gap-3"><div><h3 className="font-black">{part.description}</h3><p className="text-sm text-slate-500">Parte/OEM: {part.partNumber}{part.partBrand ? ` · ${part.partBrand}` : ""}</p></div><strong className="text-blue-800">{part.quantity} × USD {Number(part.unitValueUsd).toFixed(2)}</strong></div><p className="mt-3 text-sm"><b>Compatible:</b> {part.make.name} {part.model.name}, {part.yearFrom === part.yearTo ? part.yearFrom : `${part.yearFrom}–${part.yearTo}`}{part.engine ? ` · ${part.engine}` : ""}</p>{part.weightKg != null && <p className="mt-1 text-xs text-slate-500">Peso unitario: {Number(part.weightKg)} kg</p>}</article>)}</Section>; }
